name = "cf-functions-demo"
main = "build/worker/shim.mjs"
compatibility_date = "2024-12-13"
vars = { ENVIRONMENT = "development" }
## Enable the test domain provided by cloudflare: WORKER_NAME.SERVER_ID.workers.dev
workers_dev = true

[build]
command = "worker-build --release"

[env.production]
workers_dev = false
route = "example.com/*"

