[package]
name = "config"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = "0.12.1"
clap = { version = "4.5.23", features = ["derive", "env"] }
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
